name: Build and Release nos-core (.deb)

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout of the code
        uses: actions/checkout@v4

      - name: Installation of Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Installation of cargo-deb
        run: cargo install cargo-deb

      - name: Compilation and creation of the package .deb
        run: |
          cargo build --release
          cargo deb --no-build

      - name: Publication on GitHub Releases
        uses: softprops/action-gh-release@v2
        with:
          files: target/debian/*.deb
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}